### ISSUE TITLE
Consider dropping Compose requirement?

### ISSUE THREAD

**Issue by tbreloff** [IainNZ/GraphLayout.jl#18]
I was wondering if you might consider treating Compose in the same way you treat Jump, by wrapping Compose-specific code in a `@require` block.  If the end user does not need/want to draw with Compose, then it adds a really heavy dependency burden.  I only want to make those changes if you'd  merge them of course...

**Comment by IainNZ** [comment]
I really don't like the `@require` dependency, so my plan (eventually) was to drop the JuMP implicit requirement and replace it with specific algorithms described in the literature (rather than solving the LPs/IPs with a general solver). So I wouldn't really want to make it conditional. I also don't think its very heavy, as Compose only depends on 9 packages in total transitively, none of them with binary deps I think, and the direct deps (`Colors,Compat,DataStructures,Iterators,JSON,Measures`) are pretty commonly installed or useful packages in their own right.
